name: Tests and Coverage Reporting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Testing on Ubuntu-Latest with Python version 3.8
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@master
        
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: x64

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests with coverage and create report as xml file
        run: py.test --cov-report xml:cov.xml  --cov=validateuserdata tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
            token: ${{secrets.CODECOV_TOKEN}}
            file: cov.xml
